-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.SEDemo...';END$$;
DROP TABLE public."SEDemo";

SET check_function_bodies = true;
