-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.noprimary...';END$$;
DROP TABLE public.noprimary;

SET check_function_bodies = true;
