-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.Invoices...';END$$;
CREATE TABLE public."Invoices" (
    "invoiceID" int2vector NOT NULL,
    amt money NOT NULL
);
ALTER TABLE public."Invoices" ADD CONSTRAINT "Invoices_pkey" PRIMARY KEY ("invoiceID");
ALTER TABLE public."Invoices" OWNER TO postgres;

SET check_function_bodies = true;
