-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.noprimary...';END$$;
CREATE TABLE public.noprimary (
    col1 bigint
);
ALTER TABLE public.noprimary OWNER TO postgres;

SET check_function_bodies = true;
